### ISSUE TITLE
Video Coordination

### ISSUE THREAD

**Issue by meljeans** [sparkbox/girlscancode.io#49]
- [x] Contact Info for Videographer from Joday
- [x] List of What To Record
- [x] List of People to Teach
- [x] Meet with Ben on Thursday to review questions.
- [ ] Overall setup - can we overlay/edit slides while we're presenting?
- [x] Setting, lighting, sound
- [x] Trial Run
- [x] Talk to Ryan and Ben about setup

**Comment by meljeans** [comment]
Our video editor is Molly Bellanco, and she’s awesome. Contact her at mevideography@gmail.com. @catheraaine

**Comment by catheraaine** [comment]
Is there budget for this? Am I good to email Molly and see what she needs from us?

**Comment by catheraaine** [comment]
@kaseybon when you have a curriculum list, I can start making a list of videos necessary.

**Comment by meljeans** [comment]
Ben: 

- [ ] How should we record?
- [ ] How should we show slides? Can overlay?
- [ ] Budget restrictions?
- [ ] Date/time.

**Comment by meljeans** [comment]
Closing & replacing with individual issues.
