### ISSUE TITLE
Finalize Groups Links

### ISSUE THREAD

**Issue by meljeans** [sparkbox/girlscancode.io#63]
The "Continue Learning" page will have a section for Groups or Meetups that the girls can join to keep learning more. Can you help finalize the list? Here's our first pass:

## Groups
- Girls Teaching Girls to Code - http://www.girlsteachinggirlstocode.org/index.html 
- Made w/ Code by Google - https://www.madewithcode.com/ 
- High School Code Camp - https://squareup.com/code-camp/high-school 
- Girls Who Code - https://girlswhocode.com/ 
- Hour of Code - https://hourofcode.com/us 
- Code.org - https://code.org/ 
- Tech Bridge Girls - http://www.techbridgegirls.org/
- Meetup.com - https://www.meetup.com/
- Girl Develop It (18+) - https://www.girldevelopit.com/
- Black Girls Code - http://www.blackgirlscode.com/
- Her Ideas in Motion - http://www.herideasinmotion.com/
- Girlstart - http://www.girlstart.org/
- Tech-Girls - http://www.tech-girls.org/
- CodeHS - https://codehs.com/

**Comment by catheraaine** [comment]
@meljeans updated!!

**Comment by meljeans** [comment]
Looks good!

**Comment by amunhofen** [comment]
@zastrow we are closing this issue but you may want to open it back up when you code out this section of the website. These are the links we'll use for "Continue Learning/Resources" section.
